name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  postgres: ^2.4.5
  shelf: ^1.3.1
  shelf_modular: ^2.0.0-dev.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
